import type { Metadata } from "next";
import Link from "next/link";
import PageHero from "@/components/PageHero";
import { Check, ShieldCheck, Sun, Battery } from "lucide-react";

export const metadata: Metadata = {
  title: "Solar Battery Storage | Pylon Energy",
  description: "Maximise solar efficiency. Premium home battery storage systems including Tesla Powerwall, Sungrow, and Alpha ESS. Clean energy 24/7.",
};

const brands = [
  { id: "tesla", name: "Tesla Powerwall 3", capacity: "13.5 kWh", type: "Liquid-cooled LFP", warranty: "10 Years", desc: "The gold standard in home storage. Excellent monitoring, integrated gateway, and full blackout backup support." },
  { id: "sungrow", name: "Sungrow SBR", capacity: "9.6 – 25.6 kWh", type: "High-Voltage LFP", warranty: "10 Years", desc: "Modular stackable battery system. Expandable over time, perfect pairing for Sungrow hybrid inverters." },
  { id: "alpha-ess", name: "Alpha ESS Smile", capacity: "10.1 – 20.2 kWh", type: "LFP Chemistry", warranty: "10 Years", desc: "All-in-one residential energy storage. Robust design, competitive pricing, built for outdoor installations." },
  { id: "growatt", name: "Growatt HOPE", capacity: "5.0 – 20.0 kWh", type: "Lithium Iron Phosphate", warranty: "10 Years", desc: "Highly economical modular energy storage system. Flexible capacity expansion and seamless integration with Growatt inverters." },
  { id: "enphase", name: "Enphase IQ Battery 5P", capacity: "5.0 kWh", type: "LFP Chemistry", warranty: "15 Years", desc: "The most reliable all-in-one AC-coupled storage battery. Longest warranty in the industry with microinverter redundancy." },
  { id: "goodwe", name: "GoodWe Lynx Home U", capacity: "5.4 – 32.4 kWh", type: "Low-Voltage LFP", warranty: "10 Years", desc: "Safe and modular low-voltage battery system. Smart diagnostic tools, excellent for GoodWe hybrid systems." },
];

export default function SolarBatteries() {
  return (
    <>
      <PageHero
        title="Solar Battery Storage"
        subtitle="Protect your household from power blackouts, reduce grid reliance to near zero, and store daytime solar power for evening use."
        breadcrumbs={[{ label: "Services", href: "/services" }, { label: "Solar Batteries" }]}
      />

      {/* Intro */}
      <section className="section-padding bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <p className="section-label">ENERGY STORAGE</p>
              <h2 className="section-title">Store the Sun, Power the Night</h2>
              <p className="text-pe-gray-500 leading-relaxed mb-6">
                Without a solar battery, any excess energy generated by your solar system during the day is sent back to the grid for a minimal feed-in tariff. Adding battery storage keeps that energy in your home, allowing you to use it when grid prices are highest.
              </p>
              
              <ul className="space-y-3 mb-8">
                {["Store excess solar power automatically", "Maintain power during grid blackouts", "Maximise your self-consumption metrics", "Participate in Virtual Power Plants (VPP)"].map((b, i) => (
                  <li key={i} className="flex items-center gap-2 text-pe-gray-700 font-medium">
                    <Check size={18} className="text-pe-green" />
                    {b}
                  </li>
                ))}
              </ul>
            </div>
            
            <div className="relative">
              <div className="rounded-3xl overflow-hidden min-h-[350px] p-8 flex flex-col justify-between text-white"
                style={{ background: "linear-gradient(135deg, #002B5C 0%, #001A3A 100%)" }}>
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-white/10 rounded-2xl flex items-center justify-center">
                    <Battery size={24} className="text-pe-cyan" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg">Solar Battery Savings</h3>
                    <p className="text-white/60 text-xs">Maximize Energy Independence</p>
                  </div>
                </div>
                
                <div className="my-8">
                  <p className="text-[11px] uppercase tracking-wider text-white/40 mb-1">Typical Grid Offset</p>
                  <p className="text-4xl font-black text-pe-green font-mono">Up to 95%</p>
                </div>
                
                <Link href="/get-quote" className="btn-primary w-full justify-center">
                  Get Battery Proposal →
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Brands Grid */}
      <section className="section-padding bg-pe-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="section-title">Premium Brands We Carry</h2>
            <p className="section-subtitle mx-auto">We only install batteries certified by the Solar Accreditation Australia for maximum safety and performance.</p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {brands.map((b, i) => (
              <div
                key={i}
                id={b.id}
                className="card p-8 flex flex-col justify-between scroll-mt-24 border border-slate-100 hover:border-[#29ABE2]/50 hover:shadow-lg transition-all duration-300"
              >
                <div>
                  <div className="flex justify-between items-start mb-4">
                    <h3 className="text-xl font-bold text-pe-navy">{b.name}</h3>
                    <span className="text-xs bg-pe-orange-light text-pe-orange font-bold font-mono px-2 py-0.5 rounded-full border border-pe-orange/10">
                      {b.capacity}
                    </span>
                  </div>
                  <p className="text-xs text-pe-gray-400 mb-4">{b.type} &middot; Warranty: {b.warranty}</p>
                  <p className="text-pe-gray-500 text-sm leading-relaxed mb-6">{b.desc}</p>
                </div>

                <Link href={`/get-quote?battery=${b.name}`} className="btn-navy w-full justify-center">
                  Request Pricing Details →
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
